server:
  port: 9004
spring:
  config:
    import: "vault://"
  application:
    name: lecture-service
  cloud:
    vault:
#      uri: http://team-vault:8200
      uri: http://localhost:8200
      token: myroot
      kv:
        enabled: true
        backend: secret
        application-name: lecture-service
        profile-separator: '/'
        version: 2
  datasource:
#    url: jdbc:mysql://team-mysql:3306/lecture?allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mysql://localhost:3307/lecture?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB        # 단일 파일 최대 크기
      max-request-size: 250MB

cloud:
  aws:
    credentials:
      access-key: AKIA4ZPZVM5RZEZJRN5J
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: aigongbu-lecture-files

file:
  upload-dir: "C:/upload_files"

team:
#  auth-service-url: http://auth-service:9001
  auth-service-url: http://localhost:9001

logging:
  level:
    org.springframework.cloud.vault: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
