name: lecture-service

replicaCount: 1               # HPA 안 쓸 경우 수동 복제 수 지정

nodeSelector:
  nodegroup-type: first

image:
  repository: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/aigongbu/service-images
  tag: c2369a93cee7401b1f41ad194fb33ebdcdc022a7
  pullPolicy: IfNotPresent

containerPort: 80

resources:                    # 오토 스케일 기반 마련
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi

service:
  protocol: TCP
  port: 80
  targetPort: 80
  type: ClusterIP

hpa:
  enabled: false
