name: Java CI with Gradle

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3308:3306
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: lecture
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print unresolved placeholders
        run: grep -r '\${' src/main

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          for i in {1..30}; do
            if mysqladmin ping -h"127.0.0.1" -uroot -p1234 --silent; then
              echo "MySQL is up!"
              break
            fi
            sleep 2
          done

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Generate Jacoco coverage report
        run: ./gradlew jacocoTestReport

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true
